import { Lora } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Head from 'next/head';
import logo from "@/public/logo.svg"
import Footer from "@/components/Footer/Footer";
import { Providers } from "@/components/StoreProvider/StoreProvider";
const lora = Lora({
  subsets: ["latin"],
});


export const metadata = {
  icons: {
    icon: '/logo.svg', // Corrected path
  },
  title: "Oak & Iron",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <Head>
        <link rel="icon" href={logo} />
      </Head>
     <Providers>
     <body
        className={lora.className}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
     </Providers>
    </html>
  );
}
